# Generated by Django 4.2.5 on 2024-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remember_me',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
